config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'welcome/index'

  root 'welcome#index'

  resources :users

  resources :rides

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ride.rb
class Ride < ApplicationRecord
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string
#  email           :string
#  password_digest :string
#  status          :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  has_secure_password


  before_save { email.downcase! }
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: { case_sensitive: false }

  #
  # validates :password, presence: true, length: { minimum: 3 }


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController

  def index
    @rides = Ride.all
  end

  def new
    @ride = Ride.new
  end

  def create
    @ride = Ride.new(rider_params)
    if @ride.save
      # session[:user_id] = @ride.id
      redirect_to '/rides'
    else
      render 'new'

    end
  end

  def show
    @ride = Ride.find(params[:id])
  end

  private
  def rider_params
    params.require(:ride).permit(:ride_name, :date, :milage, :start_info, :description)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      render 'new'

    end
  end

  def show
    @user = User.find(params[:id])
  end




    private
    def user_params
      params.require(:user).permit(:name, :email, :password_digest)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rides_helper.rb
module RidesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?
    !current_user.nil?
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CityCycling1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rides/index.html.erb
<% @rides.each do |ride| %>

  <p>Ride Name: <%= ride.ride_name %></p>
  <p>Date: <%= ride.date %></p>
  <p>Milage: <%= ride.milage %></p>

  <% if logged_in? && current_user.status == "active" %>
  <p>Start Info: <%= ride.start_info %></p>
  <% else %>
  <p>Log in for start info </p>
  <% end %>

  <p>Description: <%= ride.description %></p>
  <%= link_to ride.ride_name, ride_path(ride) %>
  <br><br>

<% end %>

app/views/rides/new.html.erb
<h1>rides/new</h1>
<p style="color:red"><%= @ride.errors.full_messages if @ride.errors.any? %></p>

<%= form_for(@ride) do |f| %>
  <%= f.label :ride_name %>
  <%= f.text_field :ride_name %>

  <%= f.label :date %>
  <%= f.date_field :date %>

  <%= f.label :mileage %>
  <%= f.number_field :milage %>

  <%= f.label :start_info, :start_info %>
  <%= f.text_field :start_info %>

  <%= f.label :description, :description %>
  <%= f.text_field :description %>

  <%= f.submit %>
<% end %>

app/views/rides/show.html.erb
<p><%= @ride.ride_name %></p>
<p><%= @ride.date %></p>
<p><%= @ride.milage %></p>

<% if logged_in? && current_user.status == "active" %>
<p>Start Info: <%= @ride.start_info %></p>
<% elsif logged_in? %>
<p>Sign up for this ride to see start info </p>
<% else %>
<p>log in</p>
<% end %>

<p><%= @ride.description %></p>

<%= link_to "New Ride", new_ride_path %>

<%= link_to 'Log Out', logout_path, method: :delete %><br>
<%= link_to 'Log In', '../login' %>

app/views/users/new.html.erb
<h1>users/new</h1>
<p style="color:red"><%= @user.errors.full_messages if @user.errors.any? %></p>

<%= form_for(@user) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password_digest %>

  <%= f.label :password_confirmation, "Confirmation" %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<p><%= @user.name %></p>
<p><%= @user.email %></p>
<p><%= @user.status || "none" %></p>

<%= link_to "New User", new_user_path %>

app/views/welcome/index.html.erb
<!-- <h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p> -->

<h1>Hello Rails</h1>